# Generated by Django 4.2.7 on 2023-11-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=15, verbose_name='Devices')),
                ('ip_addr', models.CharField(max_length=15, verbose_name='IP Address')),
                ('fabricante', models.CharField(choices=[('Cisco System', 'Cisco System'), ('Huawei', 'Huawei'), ('H3C', 'H3C')], max_length=15, verbose_name='Manufacture')),
            ],
            options={
                'db_table': 'Devices',
            },
        ),
    ]
